name: CI/CD for Lambda Functions

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: ["influxdb-monthly-backup", "influxdb-daily-backup", "influxdb-monthly-restore", "influxdb-daily-restore"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Virtual Environment
        run: |
          cd ${{ matrix.lambda }}
          python3 -m venv test-venv

      - name: Install Dependencies
        run: |
          cd ${{ matrix.lambda }}
          source test-venv/bin/activate
          pip install --upgrade pip
          pip install pylint pytest
          pip install -r requirements.txt

      - name: Run Pylint for Code Quality Check
        run: |
          cd ${{ matrix.lambda }}
          source test-venv/bin/activate
          pylint *.py --fail-under=6.5

      # - name: Run Unit Tests
      #   run: |
      #     cd ${{ matrix.lambda }}
      #     source test-venv/bin/activate
      #     pytest tests
